# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.form.registration:
      class: AuthBundle\Form\UserType
      tags:
        - { name: form.type, alias: app_user_registration}

    app.form.user.role:
      class: AuthBundle\Form\TeamRoleType
      arguments: ["@security.authorization_checker", '@security.token_storage']
      tags:
        - { name: form.type }

    app.usertype.pilote:
      class: AuthBundle\Form\UserType
      arguments: ['@security.authorization_checker']
      tags:
        - { name: form.type }

    role_voter:
        class: AuthBundle\Security\RoleVoter
        tags:
          - { name: security.voter }

    team_voter:
        class: AuthBundle\Security\TeamVoter
        tags:
          - { name: security.voter }