<?php

namespace AuthBundle\Repository;

/**
 * TeamRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
