<?php

namespace AuthBundle\Repository;

use AuthBundle\Entity\Equipe;
use Doctrine\ORM\EntityRepository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByTeam(Equipe $equipe)
    {
        return $this->createQueryBuilder('u')


            ->innerJoin('u.teamRoles', 'teamRoles')
            ->innerJoin('teamRoles.equipe', 'equipe')
            ->where('equipe = :equipe')
            ->setParameter('equipe', $equipe)
            ->getQuery()
            ->getResult();
    }


}

//SELECT ihni_user.username
//FROM ihni_user
//INNER JOIN team_role
//ON ihni_user.id = team_role.user_id
//INNER JOIN equipe
//ON equipe.id = team_role.equipe_id
//WHERE equipe.id = 2